body:
  - type: markdown
    attributes:
      value: |
        감사합니다! Python-KIS 커뮤니티에 질문을 제출해주셨습니다.
        다른 사용자들을 도와드릴 수 있도록 최대한 자세하게 설명해주세요.

  - type: textarea
    id: description
    attributes:
      label: "질문 내용"
      description: "어떤 문제가 있나요? 최대한 자세하게 설명해주세요."
      placeholder: |
        예: "quote() 메서드를 호출했을 때 None이 반환됩니다.
        다음과 같이 코드를 작성했습니다..."
      required: true

  - type: textarea
    id: code
    attributes:
      label: "재현 코드"
      description: "문제를 재현할 수 있는 최소한의 코드를 제공해주세요."
      language: python
      placeholder: |
        from pykis import PyKis
        pykis = PyKis(mock=True)
        stock = pykis.stock("005930")
        quote = stock.quote()
        print(quote)
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: "환경"
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "기타"
      required: true

  - type: textarea
    id: context
    attributes:
      label: "추가 정보"
      description: |
        다음 정보를 포함해주세요:
        - Python 버전: (예: 3.9)
        - pykis 버전: (예: 2.2.0)
        - OS:
        - 에러 메시지 (있으면):
      placeholder: |
        Python 3.11
        pykis 2.2.0
        Windows 11
        ConnectionError: ...
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "확인 사항"
      options:
        - label: "FAQ를 읽었습니다"
          required: false
        - label: "유사한 이슈를 검색했습니다"
          required: false
        - label: "최신 버전을 사용하고 있습니다"
          required: false
