from types import SimpleNamespace

from pykis.api.websocket import order_book
from pykis.api.websocket import price as ws_price


class FakeTicket:
    def __init__(self, id=None, key=None):
        self.id = id
        self.key = key


class FakeClient:
    def __init__(self):
        self.calls = []

    def on(self, **kwargs):
        self.calls.append(kwargs)
        return FakeTicket(kwargs.get("id"), kwargs.get("key"))


def test_on_order_book_dispatch_for_domestic_and_foreign():
    """on_order_book dispatches the correct id and key for KRX and foreign markets."""
    fake = FakeClient()

    # domestic
    t_dom = order_book.on_order_book(fake, "KRX", "SYM", lambda *_: None)
    assert t_dom.id == "H0STASP0"
    assert t_dom.key == "SYM"

    # foreign (NASDAQ)
    t_for = order_book.on_order_book(fake, "NASDAQ", "AAPL", lambda *_: None, extended=True)
    assert t_for.id in ("HDFSASP0", "HDFSASP1") or isinstance(t_for.id, str)
    # key should be generated by build_foreign_realtime_symbol
    assert isinstance(t_for.key, str) and t_for.key[0] in ("R", "D")


def test_on_product_order_book_forwards():
    """on_product_order_book should forward to on_order_book via product.kis.websocket."""
    prod = SimpleNamespace()
    prod.market = "KRX"
    prod.symbol = "XYZ"
    prod.kis = SimpleNamespace(websocket=FakeClient())

    ticket = order_book.on_product_order_book(prod, lambda *_: None)
    assert ticket.id == "H0STASP0"
    assert ticket.key == "XYZ"
